### ISSUE TITLE
Snow melting not working as intended

### ISSUE THREAD

**Issue by Pumpk1in** [JimiIT92/BetterSnowierSnow#2]
**Describe the bug**
You can have a description here : https://www.spigotmc.org/threads/better-snowier-snow.489766/#post-4597398

But to summarize, the snow layers seems to never melt.
Instead, it will just replace the grass (and so,remove the snow texture on the sides) with dirt blocks below the snow layers. Strange behavior !
Also, it seems the generated config is missing some setings, like snowMeltBlocks

**To Reproduce**
Nothing special, I ran a map for month with the plugin in v1.1, so there is now a lot of snow layers waiting to melt. (max pile height was set on 3). I used the same settings but increased the max pile height to 4. And did not forget to set false for noMeltInColdBiomes

**Expected behavior**
Snow layers removed.
Snowy grass blocks below remaining here until the last snow layer removed. Or never if we set the config to never melt the last layer of snow.

**Screenshots**
You can see it on spigot forum topic

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Plugin 1.2

Thank you a lot !

**Comment by Pumpk1in** [comment]
Since that issue I have not been able to reproduce the bug with grass.
Maybe I had messed up the config.

**But I'm back to the first issue : no melting at all.**
With snowMeltPercentage: 1.0  snowMeltMinLayers: 1 noMeltInColdBiomes: false

**Comment by Pumpk1in** [comment]
I just saw that, snow no more melt with lantern/torch close to it.
Even if noMeltInColdBiomes: false and snowMeltMinLayers: 0 (it should still melt with snowMeltMinLayers: 1)

Melting is just totally broken haha

**Comment by JimiIT92** [comment]
Hi, sorry if I only respond now, I've missed this issue since I was away from home. Anyway I've seen the spigot post but the images are no longer available, and I've tried different settings on a 1.20.2 server. If I have the `noMeltInColdBiomes` set to true, the snow layers doesn't melt, while if I set to false they will melt until they reach the `snowMeltMinLayers`, which when set to 1 will mimic the vanilla behavior.

Can you provide extra details, or event the config file you are using, so I can see what's going on using your exact configuration? Thank you :)

**Comment by helpimnotdrowning** [comment]
Hi, I'm also having the same problem. Surrounded by torches, none of the snow seems to melt.
Config file:
```yml
# Make snow blocks and layers falling if the block below
# is removed. Also make snow blocks drop 2 snowballs if
# broken by falling on a non-solid block
snowGravity: false
# Make snow not melting in cold biomes
noMeltInColdBiomes: false
# The maximum light level at which snow won't melt
# Setting this to 15 will prevent snow from melting at all
# If 'noMeltInColdBiomes' is true, this value will be ignored
# at all in cold biomes.
# Negative values will be ignored and 0 will be used as value
# Values above 15 will be ignored and 15 will be used as value
meltAboveLightLevel: 7
# Prevent grass from decaying if is snowy
noSnowyGrassDecay: true
# Prevent grass from spreading if is snowy
noSnowyGrassSpread: true
# The rate at which the snow could pose.
# If set to 1, snow posing will be every x ticks,
# where x is the amount of ticks specified by the
# 'snowPoseFrequency' setting.
# Minecraft default chance is 1/16.
# Setting this to 0 will prevent snow from posing at all.
# WARNING: setting this to a high value
# may be memory consuming and cause lag
snowChancePercentage: 0.0625
# How often the snow could pose.
# Higher values will make it slower.
# Lower values will make it faster.
# WARNING: setting this to a really lower value
# may be memory consuming and cause lag
snowPoseFrequency: 20
# The maximum amount of snow layers
# that can be naturally posed by snowing.
# Values above 7 will be ignored and 7 will
# be used as value.
# Also negative values will be ignored and 0 will
# be used as value
snowPoseMaxLayers: 7
# How many snow layers will be posed per ticks.
# Negative values will be ignored and 1 will be used as value.
# Any value above 256 will be ignored and 256 will be used as value.
snowPoseBlocks: 1
# List of worlds where the snow pose will have effect.
# This is valid only for snow being posed by snowing,
# other settings, such as the "slowness on walking" are unaffected
# and will work in any world regardless of this list
snowPoseWorlds:
- world
# List of chunks where snow will not be posed at all.
# Syntax: x1,z1,x2,z2,true|false - exclude a rectangle region
# around the diagonal from the chunks set. Last parameter
# will set if also vanilla snow pose (the first layer) will
# be canceled in those chunks
snowPoseIgnoredChunks:
- 0,0,0,0,false
# Add a slowness effect to players walking on snow
# blocks or snow layers. For layers you can set the
# minimum amount for which the effect will be applied.
# For instance, if setting to 2, players walking on
# a single snow layer won't get the effect.
# Setting this to 1 will give the effect regardless
# of how many layers there are.
# For min layers, negative values will be ignored
# and 0 will be used as value.
# For min layers, values above 7 will be ignored
# and 7 will be used as value.
# WARNING: this may be memory consuming
slownessOnSnow: false
slownessMinLayers: 1
slownessStrength: 1
# Prevent slowness effect (if active) from being applied
# if the player is sneaking
slownessSneakingPrevent: false
# Set to use metrics to collect plugin usage information
metrics: false
# The rate at which the snow could melt.
# If set to 1, snow melting will be every x ticks,
# where x is the amount of ticks specified by the
# 'snowMeltFrequency' setting.
# Setting this to 0 will prevent snow from melting at all.
# The snow could melt only if the light level is above the
# 'meltAboveLightLevel' value.
# WARNING: setting this to a high value
# may be memory consuming and cause lag
snowMeltPercentage: 1
# The minimum amount of snow layers
# that can be left posed by melting.
# Values below 0 or negative will be ignored and 0 will
# be used as value.
# Also values above 7 will be ignored and 7 will be used as value.
snowMeltMinLayers: 0
# ADDED BY ME, NOT PRESENT NORMALLY BUT MENTIONED ON LINE 80
snowMeltFrequency: 10
```

![image](https://github.com/JimiIT92/BetterSnowierSnow/assets/35247379/b94adead-afc0-4b6f-8005-83ddd52145b7)

Running:
* Purpur 1.20.1 build 2062
* BetterSnowierSnow 1.3-1.20.1
